# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-11 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='img',
            field=models.ImageField(blank=True, default='static/upload/default.png', null=True, upload_to='static/upload/', verbose_name='景点图片'),
        ),
    ]
