# Generated by Django 5.1.2 on 2024-12-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0004_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="view",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="详细地址"
            ),
        ),
    ]
