# Generated by Django 5.1.2 on 2024-12-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0005_view_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "food_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("food_name", models.CharField(max_length=100)),
                ("food_desc", models.TextField(verbose_name="美食描述信息")),
                (
                    "food_img",
                    models.ImageField(
                        blank=True,
                        default="static/food/default.png",
                        null=True,
                        upload_to="static/food/",
                        verbose_name="美食图片",
                    ),
                ),
                ("food_price", models.FloatField(default=0, verbose_name="美食价格")),
                ("food_rate", models.CharField(max_length=5, verbose_name="美食评分")),
                ("f_province", models.CharField(max_length=20, verbose_name="省份")),
                (
                    "f_city",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="城市"
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "美食",
                "verbose_name_plural": "美食",
                "ordering": ["-food_id"],
            },
        ),
    ]
