# Generated by Django 5.1.2 on 2024-12-12 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0008_alter_food_food_rate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="view",
            new_name="food",
        ),
    ]
