# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-11 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '旅游攻略',
                'verbose_name_plural': '旅游攻略',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='ExtUser',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('sex', models.CharField(blank=True, max_length=2, null=True, verbose_name='性别')),
                ('address', models.CharField(blank=True, max_length=30, null=True, verbose_name='地址')),
                ('autograph', models.CharField(blank=True, max_length=50, null=True, verbose_name='个性签名')),
                ('greet', models.CharField(blank=True, max_length=50, null=True, verbose_name='问候语')),
                ('labels', models.CharField(blank=True, max_length=50, null=True, verbose_name='标签')),
                ('register_date', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='酒店名称')),
                ('pic', models.ImageField(upload_to='static/upload/', verbose_name='图片')),
                ('intro', models.TextField(verbose_name='简介')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
                ('tel', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
            ],
            options={
                'verbose_name': '酒店',
                'verbose_name_plural': '酒店',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0, verbose_name='门票价格')),
                ('province', models.CharField(max_length=20, verbose_name='省份')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('view_name', models.CharField(max_length=25, verbose_name='景点名称')),
                ('view_desc', models.TextField(verbose_name='景点描述信息')),
                ('view_rate', models.CharField(max_length=5, verbose_name='景点打分')),
                ('advise_time', models.CharField(max_length=20, verbose_name='建议游玩时间')),
            ],
            options={
                'verbose_name': '景点',
                'verbose_name_plural': '景点',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='score',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.View'),
        ),
        migrations.AddField(
            model_name='comment',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.View'),
        ),
    ]
